global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: game
    static_configs:
      - targets: ["game:8082"]

  - job_name: lobby
    static_configs:
      - targets: ["lobby:8081"]
